# Generated by Django 5.1.1 on 2025-07-16 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 16, 8, 42, 48, 708409, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
